### ISSUE TITLE
Blizzard output

### ISSUE THREAD

**Issue by neerajkuhike** [ming024/FastSpeech2#12]
The output of Blizzard dataset  is not good , which is sample at 16khz. Have you tested the model for 16hz sampled audio.

**Comment by ming024** [comment]
@neerajkuhike actually I haven't tried Blizzard since my 5-th commit and that's one month ago... Maybe hyperparameter-tuning is necessary, but I think an even more crucial problem is vocoding. As I know, the MelGAN and WaveGlow available online are trained on the **LJSpeech** dataset, so there must be a large performance drop if directly used on another dataset without finetuning or re-training....
I believe that the performance drop of MelGAN will be even larger then WaveGlow since it is a GAN-based model and it never seen the mel-spectrogram of Blizzard at training time.

**Comment by keonlee9420** [comment]
@neerajkuhike In my last experiments on Blizzard2013 dataset, as @ming024  said, vocoding with WaveGlow pretrained on LJSpeech is more robust and acceptable than MelGAN. And I can confirm that it is also true for this FastSpeech2 implementation. The key is sampling rate and only thing to do is resampling Blizzard datasets with 22050Hz, and setup audio related hyperparameters. Then waveglow should fine with it. Hope this helps.

**Comment by ming024** [comment]
closed #12
