### ISSUE TITLE
does the mel_fmax matter ？

### ISSUE THREAD

**Issue by yileld** [ming024/FastSpeech2#37]
I saw “please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder” about mel_fmax in preprocess.yaml
But I didnt change it when using MelGAN, it seems not bad.
Why mel_fmax is different in hifigan and melgan？

**Comment by ming024** [comment]
@yileld It's a parameter of the mel filters. This parameter is set to different values since the preprocessing settings of MelGAN and HiFi-GAN are different. While the resulted mel-spectrogram may not differ a lot, you can try to compute the mel-spectrogram of a ground-truth wav with ``mel_fmax=8000`` and convert it back to the waveform with MelGAN, and you should notice that the pitch will be slightly different.

**Comment by ming024** [comment]
closed #37
