### ISSUE TITLE
Why perform interpolation on pitch?

### ISSUE THREAD

**Issue by OlaWod** [ming024/FastSpeech2#48]
https://github.com/ming024/FastSpeech2/blob/7011fa1b86239a49a9154a5fcea45474c947acb1/preprocessor/preprocessor.py#L207

![IMG_0595(20210415-001729)](https://user-images.githubusercontent.com/32514635/114744978-cf0c5a00-9d80-11eb-8a3f-fb6d3068477e.PNG)

As far as I know, pitch(F0) is the bottom yellow line on the spectrogram, and the pitch before interpolation looks similar to it. What's the reason to perform interpolation on pitch?

**Comment by ming024** [comment]
@OlaWod I do this trick because the F0 detecting algorithm is not always accurate, sometimes it cannot detect the F0 of a voiced frame and give it a zero. It is also arguable if it is reasonable to set the F0 of an unvoiced frame to zero. However, this is only an engineering trick and I believe there are better solutions to this problem.
