### ISSUE TITLE
Is the predicted wav realy better than fastspeech1?

### ISSUE THREAD

**Issue by Liujingxiu23** [ming024/FastSpeech2#53]
I tried to train on my own dataset, but the result is not as good as I expected, and even worse than fastspeech1.    I use default setting , phone-level,  with hifigan as vocoder
How about your results?

**Comment by ming024** [comment]
@Liujingxiu23 how is the quality and size of your dataset? If the quality is even worse than FastSpeech 1, maybe you should check the correctness of the pitch values given by the DIO algorithm (or any other algorithm you used).

**Comment by Liujingxiu23** [comment]
@ming024  thank you for your reply. I trained multi-speaker model using 7 speakers, totally abput 4w sentences. I will compare the synthsiezed wav again carefully and check the f0 feature extracted.

**Comment by Liujingxiu23** [comment]
@ming024  The following is my loss, what it look like? I use mel-features used in hifigan vocoder.
<img width="697" alt="loss" src="https://user-images.githubusercontent.com/49260794/116333584-45d83700-a806-11eb-8e65-f486fc8ce77a.PNG">

**Comment by ming024** [comment]
@Liujingxiu23 People believe that Tacotron is better, at least according to the SOTA TTS papers. I think it is because the autoregressive models can fit better to the datasets. However, they are more difficult to train (and probably takes more computation resources) so maybe that's the reason why you find the results are not good on your datasets.

For the language transfer experiments,  one possible solution is to use pretrained speaker embedding instead of the embedding table. You can check my paper [here](https://arxiv.org/abs/2103.04088).

**Comment by Liujingxiu23** [comment]
@ming024  Thank you for your reply,  I will try "use pretrained speaker embedding instead of the embedding table".

**Comment by bheshaj96** [comment]
@Liujingxiu23, how are you using speaker embeddings for multi-speaker training of fast-speech with hidden encoder vectors?
Are you directly adding both or concatenating?

**Comment by ming024** [comment]
closed #53
