### ISSUE TITLE
Why capturing pitch and energy at phoneme level instead of frame level will give good prosody? 

### ISSUE THREAD

**Issue by skosgi242** [ming024/FastSpeech2#68]
<img width="1433" alt="Screenshot 2021-05-31 at 7 32 06 PM" src="https://user-images.githubusercontent.com/51510948/120204876-ecb95400-c246-11eb-9def-a14d9db54f39.png">

Plot on the right part of the image is generated at frame level and the left plot shows the energy and pitch averaged over phonemes. It looks like some variations are lost at phoneme level. Can you please give us intuition behind proposing predictions at phoneme level.

**Comment by ming024** [comment]
@skosgi242 you may think that the pitch value is fixed within every phoneme when ``phoneme-level`` is used. However, one thing we should know is that the decoder does not always follow the predicted pitch values strictly. Especially when ``phoneme-level`` is used, the decoder will find out that sometimes it should add some variation to the pitch value of every frame within the phoneme, instead of using the same pitch value for every frame.

On the other hand, if ``frame-level`` is used, the ground-truth pitch values are provided at training time, so the decoder will not learn to make the aforementioned variations. All the decoder has to do is simply following the ground-truth frame-level pitch values. While at inference time, the predicted frame-level pitch values may not be accurate, but the decoder still strictly follows them, and thus the pitch of the synthesized utterances will be strange for the listeners.

**Comment by skosgi242** [comment]
Thanks for the intuition. It helps.

**Comment by hhm853610070** [comment]
I hava tried the frame_level features of pitch and energy，but the synthesized audio is too bad.There are noise and strange pronounciation(wrong words or strange tone).The mel spectrogram is bad. When i use phoneme level features,the quality synthesized audio is good.The spectrogram of them(frame and phoneme) is very different, but I see the picture you show is similar.Do you know why?
